name: "Update Commit Status"
description: "Updates GitHub commit status checks using the GitHub Status API"
# Actions: Reusable scripts developed by different official vendors, market place and so on.

inputs:
  sha:
    description: "Commit SHA to update"
    required: true
  state:
    description: "Status: success, failure, pending, error"
    required: true
  context:                                                        # Label to identify the check, such as unit test, docker build and so on.
    description: "Status check context name (ex: DOCKER_BUILD)"
    required: true
  description:
    description: "Optional description for the status"
    required: false
    default: ""

runs:
  using: "composite"      #Re-usable mini workflow that you can call using uses: ./.github/actions/<folder>
  steps:
    - name: Update commit status
      shell: bash
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "Content-Type: application/json" \
          --data "{
            \"state\": \"${{ inputs.state }}\",
            \"context\": \"${{ inputs.context }}\",
            \"description\": \"${{ inputs.description }}\"
          }" \
          "https://api.github.com/repos/${{ github.repository }}/statuses/${{ inputs.sha }}"
